[package]
name = "joule-profiler-source-rapl"
version = "1.0.4"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Intel RAPL energy measurement source for joule-profiler"
keywords = ["energy", "rapl", "hardware", "powercap", "perf_event"]
readme = "README.md"

[dependencies]
joule-profiler-core.workspace = true
log.workspace = true
serde.workspace = true
thiserror.workspace = true

perf-event2 = { version = "0.7.4", optional = true }

[dev-dependencies]
serde_json.workspace = true

[features]
default = ["backend-perf", "backend-powercap"]
backend-perf = ["dep:perf-event2"]
backend-powercap = []

[lints]
workspace = true
