[package]
name = "joule-profiler-source-nvml"
version = "2.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "NVIDIA NVML-based GPU energy measurement source for joule-profiler"
keywords = ["energy", "nvml", "nvidia", "GPU", "hardware"]
readme = "README.md"

[dependencies]
joule-profiler-core.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
serde.workspace = true
humantime-serde.workspace = true

nvml-wrapper = "0.12.0"
tokio-timerfd = "0.2.0"
tokio-util = "0.7.18"
bitflags = "2.11.1"

[dev-dependencies]
tokio.workspace = true
mockall.workspace = true

[lints]
workspace = true
