[package]
name = "joule-profiler-source-procfs"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "procfs source for joule-profiler"
keywords = ["procfs", "linux", "io", "memory"]
readme = "README.md"

[dependencies]
joule-profiler-core.workspace = true
log.workspace = true
serde.workspace = true
humantime-serde.workspace = true
thiserror.workspace = true

procfs = "0.18.0"

[lints]
workspace = true
