[package]
name = "joule-profiler-injector-stdout"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
joule-profiler-core.workspace = true
thiserror.workspace = true
regex = "1.12.4"
libc = "0.2.186"

[lints]
workspace = true
