[package]
name = "joule-profiler-exporter-csv"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "CSV exporter for joule-profiler"

[dependencies]
joule-profiler-core.workspace = true
thiserror.workspace = true

csv = "1.4.0"

[lints]
workspace = true
